#define SECRET_WIFI_NAME "Truong 1"
#define SECRET_WIFI_PASSWORD "12345678"

#define MQTT_BROKER_SERVER_IP "mqtt3.thingspeak.com"

#define SECRET_MQTT_USERNAME "CwQ3FAQqAAsuMBUpNhoxGBw"
#define SECRET_MQTT_PASSWORD "vMOK+GbITyzJa8cU0EwH7z2j"
#define SECRET_MQTT_CLIENT_ID "CwQ3FAQqAAsuMBUpNhoxGBw"
#define CHANNEL_ID "2252582"
